// <auto-generated />
using System;
using ElectroCom.IntelligentInventory.InventoryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreSetup.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220125053503_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.CategoryAggregate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Product_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Manufacturer_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer_id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.StaffAggregate.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.CategoryAggregate.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.CategoryAggregate.Category", b =>
                {
                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.CategoryAggregate.ValueObjects.CategoryName", "CategoryName", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("Name")
                                .IsUnique();

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("CategoryName")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Item", b =>
                {
                    b.HasOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Product", null)
                        .WithMany("Items")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.ValueObjects.DateCode", "DateCode", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DateCode");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.ValueObjects.SerialNumber", "SerialNumber", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Serial Number");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("DateCode")
                        .IsRequired();

                    b.Navigation("SerialNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Product", b =>
                {
                    b.HasOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Manufacturer", null)
                        .WithMany("Products")
                        .HasForeignKey("Manufacturer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Enums.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Frequency");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.ValueObjects.ProductCode", "ProductCode", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProductCode");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("ProductCode")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.StaffAggregate.Staff", b =>
                {
                    b.OwnsOne("ElectroCom.IntelligentInventory.InventoryManagement.Core.StaffAggregate.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastName");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ElectroCom.IntelligentInventory.InventoryManagement.Core.ManufacturerAggregate.Product", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
